version: "3"

services:

  cooking-app:
    build: .
    container_name: cooking-app
    restart: always
    environment:
      JDBC_URL: ${JDBC_URL}
      SERVICE_USER: ${SERVICE_USER}
      SERVICE_USER_PASSWORD: ${SERVICE_USER_PASSWORD}
      SERVICE_EMAIL: ${SERVICE_EMAIL}
      SERVICE_EMAIL_PASSWORD: ${SERVICE_EMAIL_PASSWORD}
    ports:
      - "80:8080"

networks:
  default:
    external:
      name: home-network